# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Olx < Formula
  desc "A CLI tool for OLX"
  homepage "https://github.com/andresgarcia29/olx-cli"
  version "1.1.1"

  depends_on "elvish" => :optional
  depends_on "fish" => "v1.2.3"
  depends_on "git" if OS.mac?
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andresgarcia29/cli-olx/releases/download/v1.1.1/cli-olx_Darwin_x86_64.tar.gz"
      sha256 "b708eaeec5594def4032df3a2328bf1203eaf382e35b83b75f0d1b1d30060c87"

      def install
        bin.install "olx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andresgarcia29/cli-olx/releases/download/v1.1.1/cli-olx_Darwin_arm64.tar.gz"
      sha256 "f4d7aae5551278e8ddce15250312b14fd287859376ceb5a104ee764c8f027772"

      def install
        bin.install "olx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andresgarcia29/cli-olx/releases/download/v1.1.1/cli-olx_Linux_x86_64.tar.gz"
        sha256 "473a844d4c034b34341b4c720f0f02100d3b639040bf5c20b4baf40cc8ff31c1"

        def install
          bin.install "olx"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andresgarcia29/cli-olx/releases/download/v1.1.1/cli-olx_Linux_arm64.tar.gz"
        sha256 "3fd4d3f587706b29ea3206aae78bc1380dea6dc0dca749113ba9c84ab90134c1"

        def install
          bin.install "olx"
        end
      end
    end
  end

  test do
    system "#{bin}/olx", "--version"
  end
end
