# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Olx < Formula
  desc "A CLI tool for OLX"
  homepage "https://github.com/andresgarcia29/olx-cli"
  version "1.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andresgarcia29/cli-olx/releases/download/v1.1.2/cli-olx_Darwin_x86_64.tar.gz"
      sha256 "390e1d16ac0833d5889a53561cd9d3f6f9119505aad13786ed21a6c830b2b49e"

      def install
        bin.install "olx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andresgarcia29/cli-olx/releases/download/v1.1.2/cli-olx_Darwin_arm64.tar.gz"
      sha256 "20330b2fb40f571dc010ac2e3fcf5674006e89fc0727e7374ceeacab029d3b8c"

      def install
        bin.install "olx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andresgarcia29/cli-olx/releases/download/v1.1.2/cli-olx_Linux_x86_64.tar.gz"
        sha256 "c436b97998d93d7e9fff921ecc4d76478849f260f241d9fe6c9470fbd0723ce6"

        def install
          bin.install "olx"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andresgarcia29/cli-olx/releases/download/v1.1.2/cli-olx_Linux_arm64.tar.gz"
        sha256 "075b8657a0d9164007f7334c2de148fe6a289896c5d9c060ec3315af5743e8bd"

        def install
          bin.install "olx"
        end
      end
    end
  end

  test do
    system "#{bin}/olx", "--version"
  end
end
