# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Olx < Formula
  desc "A CLI tool for OLX"
  homepage "https://github.com/andresgarcia29/olx-cli"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andresgarcia29/cli-olx/releases/download/v1.2.1/cli-olx_Darwin_x86_64.tar.gz"
      sha256 "2fd47bfd15b2497b6bb30d267c7f87d4e0bdc48d0b9570d81c123c4d68046682"

      def install
        bin.install "olx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andresgarcia29/cli-olx/releases/download/v1.2.1/cli-olx_Darwin_arm64.tar.gz"
      sha256 "ad9549c00eab990791dc584245ed61e2ea5a11839c0477da22152092d54d4fe1"

      def install
        bin.install "olx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andresgarcia29/cli-olx/releases/download/v1.2.1/cli-olx_Linux_x86_64.tar.gz"
        sha256 "34099c199eec2c94e8c5cf255664ba09e6eababb85fa8a29148be9f6746705b6"

        def install
          bin.install "olx"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/andresgarcia29/cli-olx/releases/download/v1.2.1/cli-olx_Linux_arm64.tar.gz"
        sha256 "045aa74e902a10a608b17ea7be9281beaaf9aebebae072195980cb2b50cf0252"

        def install
          bin.install "olx"
        end
      end
    end
  end

  test do
    system "#{bin}/olx", "--version"
  end
end
