# This file was generated by GoReleaser. DO NOT EDIT.
cask "ark-cli" do
  name "ark-cli"
  desc "A powerful CLI tool for AWS and Kubernetes operations"
  homepage "https://github.com/andresgarcia29/ark-cli"
  version "0.5.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ark"

  on_macos do
    on_intel do
      url "https://github.com/andresgarcia29/ark-cli/releases/download/v#{version}/ark-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "7d59445616974fe91e596fe4491326db3eee99e64392a0015f1f65e14de726b0"
    end
    on_arm do
      url "https://github.com/andresgarcia29/ark-cli/releases/download/v#{version}/ark-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "47b92e6cb0df9094daa8795f7b7653450b46639e21046209bf0505531cdbc0e8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andresgarcia29/ark-cli/releases/download/v#{version}/ark-cli_#{version}_linux_amd64.tar.gz"
      sha256 "ca1d682714881fd0b1a89451d543510287e1756e9abb8f73ba49ed79d0a380b7"
    end
    on_arm do
      url "https://github.com/andresgarcia29/ark-cli/releases/download/v#{version}/ark-cli_#{version}_linux_arm64.tar.gz"
      sha256 "d3ff01b03a46377f086602428d42168755c8640988cd5374f0de4cbfa6c22f55"
    end
  end

  # No zap stanza required
end
