# This file was generated by GoReleaser. DO NOT EDIT.
cask "ark" do
  name "ark"
  desc "A powerful CLI tool for AWS and Kubernetes operations"
  homepage "https://github.com/andresgarcia29/ark-cli"
  version "0.12.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ark"

  on_macos do
    on_intel do
      url "https://github.com/andresgarcia29/ark-cli/releases/download/v#{version}/ark-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "eb89582f0ab97e0b10aa254e9cfde986ee2bd0cefb7fa9c47183fa9beac7886c"
    end
    on_arm do
      url "https://github.com/andresgarcia29/ark-cli/releases/download/v#{version}/ark-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "b72161e4f76ed4ae9718d3c855c37f7643fea0ea83d6582c5e6d178154492855"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andresgarcia29/ark-cli/releases/download/v#{version}/ark-cli_#{version}_linux_amd64.tar.gz"
      sha256 "33ba5662cd98bc8e79a4c0efb879006486644b4f13dddb584d6a3973f8febff1"
    end
    on_arm do
      url "https://github.com/andresgarcia29/ark-cli/releases/download/v#{version}/ark-cli_#{version}_linux_arm64.tar.gz"
      sha256 "b71980502faf7489b81b93176133020ab729bfc882aa0bad73c7e15a75a15ed5"
    end
  end

  # No zap stanza required
end
