# This file was generated by GoReleaser. DO NOT EDIT.
cask "ark" do
  name "ark"
  desc "A powerful CLI tool for AWS and Kubernetes operations"
  homepage "https://github.com/andresgarcia29/ark-cli"
  version "0.10.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ark"

  on_macos do
    on_intel do
      url "https://github.com/andresgarcia29/ark-cli/releases/download/v#{version}/ark-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "9898e9b1a37936c9c684c476bc1e46f9513be012e240264383c60c42b95b76a1"
    end
    on_arm do
      url "https://github.com/andresgarcia29/ark-cli/releases/download/v#{version}/ark-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "c13326ab19e7c1aabdb6d210cf51d8e62ada41dec506efdbacdf91cc71b09882"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andresgarcia29/ark-cli/releases/download/v#{version}/ark-cli_#{version}_linux_amd64.tar.gz"
      sha256 "371a5ff17ddcd9057585d7c1d0cae67c73bb0161e73075b5b6c1f48ef84ae57f"
    end
    on_arm do
      url "https://github.com/andresgarcia29/ark-cli/releases/download/v#{version}/ark-cli_#{version}_linux_arm64.tar.gz"
      sha256 "3bbe5de5a165ec71713826986207c4990c2ca5cab3e3227d826f811bfcdaa27f"
    end
  end

  # No zap stanza required
end
