# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArkCli < Formula
  desc "A powerful CLI tool for AWS and Kubernetes operations"
  homepage "https://github.com/andresgarcia29/ark-cli"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andresgarcia29/ark-cli/releases/download/v0.5.2/ark-cli_0.5.2_darwin_amd64.tar.gz"
      sha256 "617887e8f998a3d1dca837722df8012d6e716446701c6ca83e6392b09c7b688f"

      def install
        bin.install "ark"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andresgarcia29/ark-cli/releases/download/v0.5.2/ark-cli_0.5.2_darwin_arm64.tar.gz"
      sha256 "98f9ba22cf13676c082663594eede82f6620722e5f43f93de8fe453e401ddb66"

      def install
        bin.install "ark"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andresgarcia29/ark-cli/releases/download/v0.5.2/ark-cli_0.5.2_linux_amd64.tar.gz"
      sha256 "f803b9cfb18bd20cebf0d9ba352e82f6b064f74f0e1575fe402b19fec9d94798"
      def install
        bin.install "ark"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andresgarcia29/ark-cli/releases/download/v0.5.2/ark-cli_0.5.2_linux_arm64.tar.gz"
      sha256 "dfb7020e1fb6aa4058271bcba1c758c4e1df6314509a62fb84b4c6fb5a09d17e"
      def install
        bin.install "ark"
      end
    end
  end

  test do
    system "#{bin}/ark", "--version"
  end
end
